spring:
  datasource:
    product:
      url: jdbc:mysql://localhost:3306/springdatajpa2
      username: root
      password: 1234
      driverClassName: com.mysql.cj.jdbc.Driver
    employee:
#      url: jdbc:h2:mem//localhost:8083/employeedb
      url: jdbc:h2:mem:employeedb
      username: sa
      password: 1234
      driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update




