spring:
  datasource:
    product:
      url: jdbc:mysql://localhost:3306/productDB?createDatabaseIfNotExist=true
      username: nimauser
      password: 1234
      driverClassName: com.mysql.cj.jdbc.Driver
    employee:
      url: jdbc:mysql://localhost:3306/employeeDB?createDatabaseIfNotExist=true
      username: nimauser
      password: 1234
      driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update